import { useMemo, useState } from 'react';
import { Alert, Image, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Screen } from '@/src/components/Screen';
import { Badge, Button, Card, Eyebrow, Field, Subtitle, Title } from '@/src/components/UI';
import { colors } from '@/src/lib/theme';

const options = { stretch: ['Não estica', 'Estica pouco', 'Estica bastante'], touch: ['Liso e frio', 'Macio', 'Rústico'], drape: ['Fluido', 'Intermediário', 'Estruturado'], transparency: ['Opaco', 'Parcial', 'Transparente'] };
function guess(values: Record<string, string>) { const list: string[] = []; if (values.drape === 'Fluido' && values.touch === 'Liso e frio') list.push('Viscose ou crepe leve'); if (values.touch === 'Rústico' && values.drape !== 'Fluido') list.push('Linho, mistura de linho ou algodão rústico'); if (values.stretch === 'Estica bastante') list.push('Malha com elastano'); if (values.transparency === 'Transparente') list.push('Voil, organza ou tecido de baixa gramatura'); if (!list.length) list.push('Tricoline, sarja leve ou mistura plana'); return list.slice(0, 3); }
export default function Identify() {
  const [images, setImages] = useState<string[]>([]); const [values, setValues] = useState<Record<string, string>>({}); const [label, setLabel] = useState(''); const [done, setDone] = useState(false);
  const guesses = useMemo(() => guess(values), [values]);
  async function photo() { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) return Alert.alert('Permissão necessária', 'Autorize o uso da câmera.'); const result = await ImagePicker.launchCameraAsync({ mediaTypes: 'images', quality: .7 }); if (!result.canceled) setImages([result.assets[0].uri, ...images].slice(0, 6)); }
  return <Screen><View style={{ gap: 8 }}><Eyebrow>ASSISTENTE EXPERIMENTAL</Eyebrow><Title>Que tecido é este?</Title><Subtitle>As imagens e observações geram hipóteses. A composição exata depende da etiqueta, ficha técnica ou análise laboratorial.</Subtitle></View><Card><Text style={styles.section}>Registros visuais</Text><ScrollView horizontal contentContainerStyle={styles.images} showsHorizontalScrollIndicator={false}>{images.map((uri) => <Image key={uri} source={{ uri }} style={styles.image} />)}{!images.length && <View style={styles.empty}><Text>Até seis imagens</Text></View>}</ScrollView><Button label="Fotografar tecido" onPress={photo} /></Card>{Object.entries(options).map(([key, items]) => <Card key={key}><Text style={styles.section}>{({ stretch: 'Elasticidade', touch: 'Toque', drape: 'Caimento', transparency: 'Transparência' } as any)[key]}</Text><View style={styles.chips}>{items.map((item) => <Text key={item} onPress={() => { setValues({ ...values, [key]: item }); setDone(false); }} style={[styles.chip, values[key] === item && styles.active]}>{item}</Text>)}</View></Card>)}<Field label="Texto da etiqueta" value={label} onChangeText={setLabel} placeholder="Ex.: 55% linho, 45% viscose" /><Button label="Gerar hipóteses" onPress={() => setDone(true)} />{done && <Card><Badge tone="warn">Estimativa experimental</Badge><Text style={styles.section}>Hipóteses mais compatíveis</Text>{guesses.map((item, index) => <Text key={item} style={styles.guess}>{index + 1}. {item}</Text>)}{label ? <Text style={styles.note}>A etiqueta informada deve prevalecer sobre a hipótese visual: {label}</Text> : <Text style={styles.note}>Próximo passo: conferir etiqueta, origem e comportamento em teste físico.</Text>}</Card>}</Screen>;
}
const styles = StyleSheet.create({ section: { fontSize: 21, fontWeight: '600', color: colors.ink }, images: { gap: 10 }, image: { width: 180, height: 140 }, empty: { width: 180, height: 130, backgroundColor: colors.sand, alignItems: 'center', justifyContent: 'center' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, paddingHorizontal: 12, paddingVertical: 11, fontSize: 15, color: colors.ink }, active: { backgroundColor: colors.ink, color: colors.white }, guess: { fontSize: 17, lineHeight: 25, color: colors.ink }, note: { fontSize: 14, lineHeight: 22, color: colors.muted } });
