import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/src/components/Screen';
import { Badge, Button, Card, Eyebrow, Field, Subtitle, Title } from '@/src/components/UI';
import { useApp } from '@/src/context/AppContext';
import { colors } from '@/src/lib/theme';

const dimensionNames: Record<string, string> = { climate: 'Clima', water: 'Água', chemicals: 'Químicos', materials: 'Materiais', wasteCircularity: 'Resíduos', durability: 'Durabilidade' };
export default function Impact() {
  const { pieces, updatePiece, calculateImpact, impacts } = useApp();
  const [selectedId, setSelectedId] = useState<string>('');
  const piece = useMemo(() => pieces.find((item) => item.id === selectedId) || pieces[0], [pieces, selectedId]);
  const [loading, setLoading] = useState(false);
  const [carbon, setCarbon] = useState('4'); const [water, setWater] = useState('2500'); const [waste, setWaste] = useState('15'); const [durability, setDurability] = useState('40'); const [coverage, setCoverage] = useState('35'); const [confidence, setConfidence] = useState('25');
  useEffect(() => { if (!piece) return; setSelectedId(piece.id); setCarbon(String(piece.carbonKg)); setWater(String(piece.waterL)); setWaste(String(piece.wastePct)); setDurability(String(piece.durabilityUses)); setCoverage(String(piece.coverage)); setConfidence(String(piece.confidence)); }, [piece?.id]);
  const result = piece ? impacts[piece.id]?.[0] : undefined;
  async function calculate() { if (!piece) return; setLoading(true); const patch = { carbonKg: Math.max(0, Number(carbon) || 0), waterL: Math.max(0, Number(water) || 0), wastePct: Math.max(0, Number(waste) || 0), durabilityUses: Math.max(1, Number(durability) || 1), coverage: Math.max(0, Math.min(100, Number(coverage) || 0)), confidence: Math.max(0, Math.min(100, Number(confidence) || 0)) }; await updatePiece(piece.id, patch); const updated = { ...piece, ...patch }; const calc = await calculateImpact(updated); setLoading(false); Alert.alert('PI5 calculado', calc.source === 'offline' ? 'O cálculo foi feito offline e entrou na fila de sincronização.' : 'Resultado salvo na esteira PI5.'); }
  if (!pieces.length) return <Screen><Eyebrow>PHYLLOS IMPACT 5</Eyebrow><Title>Cadastre uma peça primeiro.</Title><Subtitle>O PI5 usa os dados registrados na produção para comparar o impacto na mesma escala.</Subtitle></Screen>;
  return <Screen><View style={{ gap: 8 }}><Eyebrow>PHYLLOS IMPACT 5</Eyebrow><Title>Compare impactos na escala de 0 a 5.</Title><Subtitle>Quanto maior o score, melhor o desempenho relativo à referência da categoria.</Subtitle></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pieces}>{pieces.map((item) => <Text key={item.id} onPress={() => setSelectedId(item.id)} style={[styles.pieceChip, item.id === piece?.id && styles.pieceChipActive]}>{item.name}</Text>)}</ScrollView><Card><Text style={styles.sectionTitle}>Dados da produção</Text><Field label="Carbono estimado (kg CO₂e)" keyboardType="decimal-pad" value={carbon} onChangeText={setCarbon} /><Field label="Água estimada (L)" keyboardType="decimal-pad" value={water} onChangeText={setWater} /><Field label="Perda no corte (%)" keyboardType="decimal-pad" value={waste} onChangeText={setWaste} /><Field label="Usos esperados" keyboardType="numeric" value={durability} onChangeText={setDurability} /><Field label="Cobertura dos dados (%)" keyboardType="numeric" value={coverage} onChangeText={setCoverage} /><Field label="Confiança (%)" keyboardType="numeric" value={confidence} onChangeText={setConfidence} /><Button label="Calcular PI5" loading={loading} onPress={calculate} /></Card>{result && <Card><Badge tone={result.score >= 3.5 ? 'good' : result.score >= 2.5 ? 'warn' : 'danger'}>{result.source === 'offline' ? 'Estimativa offline' : 'Modelo conectado'}</Badge><View style={styles.scoreRow}><Text style={styles.score}>{result.score}</Text><Text style={styles.outOf}>/ 5</Text></View><Text style={styles.status}>Cobertura {result.coverage}% · confiança {result.confidence}% · {result.publicationStatus}</Text>{Object.entries(result.dimensions).map(([key, value]) => <View key={key} style={styles.dimension}><View style={styles.dimensionHead}><Text style={styles.dimensionName}>{dimensionNames[key]}</Text><Text style={styles.dimensionValue}>{value}</Text></View><View style={styles.bar}><View style={[styles.fill, { width: `${Number(value) / 5 * 100}%` }]} /></View></View>)}</Card>}</Screen>;
}
const styles = StyleSheet.create({ pieces: { gap: 8 }, pieceChip: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, paddingHorizontal: 14, paddingVertical: 11, fontSize: 15, color: colors.ink }, pieceChipActive: { color: colors.white, backgroundColor: colors.ink, borderColor: colors.ink }, sectionTitle: { fontSize: 21, fontWeight: '600', color: colors.ink }, scoreRow: { flexDirection: 'row', alignItems: 'flex-end' }, score: { fontSize: 82, lineHeight: 88, fontWeight: '500', color: colors.green }, outOf: { fontSize: 24, color: colors.muted, paddingBottom: 12 }, status: { fontSize: 14, lineHeight: 21, color: colors.muted }, dimension: { gap: 6 }, dimensionHead: { flexDirection: 'row', justifyContent: 'space-between' }, dimensionName: { fontSize: 15, fontWeight: '600', color: colors.ink }, dimensionValue: { fontSize: 15, fontWeight: '700', color: colors.ink }, bar: { height: 9, backgroundColor: colors.sand }, fill: { height: 9, backgroundColor: colors.green } });
